name: dazie
description: "An offline-first group chat app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  device_info_plus: ^13.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  nearby_connections: 4.3.0
  path: ^1.9.1
  path_provider: ^2.1.6
  permission_handler: ^13.0.2
  sembast: 3.8.11
  sembast_web: 2.4.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 700
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
          weight: 400
