name: dazie
description: "An offline-first group chat and direction-finding app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
          weight: 400
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
          weight: 400
